'use strict';
const $=id=>document.getElementById(id), cfg=window.SGC_CONFIG, adminPage=!!$('admin');
let session=null,lessons=[],selected=null,refreshTimer;
const storageKey='sgc-extra-session';
function status(t){$('status').textContent=t;}
function error(e){status(e.message||String(e));}
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
async function api(path,{method='GET',body,headers={}}={}){
 const token=session?.access_token||(cfg.key.startsWith('eyJ')?cfg.key:null);
 const opts={method,headers:{apikey:cfg.key,...(token?{Authorization:'Bearer '+token}:{}),...headers}};
 if(body!==undefined){if(body instanceof File){opts.body=body;}else{opts.body=JSON.stringify(body);opts.headers['Content-Type']='application/json';}}
 const res=await fetch(cfg.url.replace(/\/$/,'')+path,opts);
 const txt=await res.text();let data;try{data=txt?JSON.parse(txt):null;}catch{data=txt;}
 if(!res.ok)throw Error(data?.msg||data?.message||data?.error_description||data?.error||'Request failed ('+res.status+')');
 return data;
}
function persist(s){session=s;if(s){session.expires_at=Date.now()+s.expires_in*1000;sessionStorage.setItem(storageKey,JSON.stringify(session));clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(()=>signout()),Math.max(1000,(s.expires_in-60)*1000));}else{sessionStorage.removeItem(storageKey);clearTimeout(refreshTimer);}}
async function refresh(){if(!session?.refresh_token)throw Error('Please sign in again.');persist(await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}}));}
async function signout(){try{await api('/auth/v1/logout',{method:'POST'});}catch{}persist(null);location.href=adminPage?'admin.html':'index.html';}
$('logout').onclick=signout;
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){error(e);}};}
$('loginform').onsubmit=safe(async e=>{e.preventDefault();status('Signing in…');persist(await api('/auth/v1/token?grant_type=password',{method:'POST',body:{email:$('email').value.trim(),password:$('password').value}}));$('password').value='';await load();});
$('reset').onclick=safe(async()=>{if(!$('email').value.trim())throw Error('Enter your email first.');await api('/auth/v1/recover?redirect_to='+encodeURIComponent(location.href.split('#')[0]),{method:'POST',body:{email:$('email').value.trim()}});status('If this account exists, a reset email will arrive shortly.');});
$('newpass').onsubmit=safe(async e=>{e.preventDefault();await api('/auth/v1/user',{method:'PUT',body:{password:$('replacement').value}});$('newpass').hidden=true;$('replacement').value='';status('Password updated.');await load();});
async function rows(table,query=''){return await api('/rest/v1/sgc_extra_'+table+'?'+query)||[];}
async function mutate(table,method,body,query='',extra={}){return api('/rest/v1/sgc_extra_'+table+'?'+query,{method,body,headers:{Prefer:'return=representation',...extra}});}
async function load(){
 if(!session)return;
 const user=await api('/auth/v1/user');session.user=user;
 $('login').hidden=true;$('logout').hidden=false;
 if(adminPage){const role=await rows('admins','user_id=eq.'+user.id);if(!role.length){status('This account is not an Academy admin.');$('admin').hidden=true;return;}$('admin').hidden=false;}
 else{$('student').hidden=false;}
 lessons=await rows('lessons','order=module_no.asc,position.asc');
 if(adminPage){renderList();status('Studio ready. Save to update the live Academy.');}
 else{const members=await rows('members','user_id=eq.'+user.id);status(members[0]?.active?'Your available modules are below. Two more unlock each month from your joining date.':'Active Academy access is required. Contact SGC Network to activate your membership.');await renderCatalog();}
}
function renderList(){const list=$('lessonlist');list.replaceChildren();for(const l of lessons){const b=el('button',`M${l.module_no} · ${l.position}. ${l.title} ${l.published?'':'(draft)'}`);b.className='secondary';b.style.cssText='display:block;width:100%;text-align:left;margin:10px 0';b.onclick=safe(()=>edit(l));list.append(b);}}
async function signed(path){const d=await api('/storage/v1/object/sign/sgc-academy-extra/'+path,{method:'POST',body:{expiresIn:3600}});const u=d.signedURL||d.signedUrl;return u.startsWith('http')?u:cfg.url.replace(/\/$/,'')+'/storage/v1'+u;}
async function renderCatalog(){const responses=await rows('responses','user_id=eq.'+session.user.id);$('catalog').replaceChildren();for(const l of lessons){const card=el('section');card.className='panel';card.append(el('span',`MODULE ${String(l.module_no).padStart(2,'0')} · SECTION ${l.position}`),el('h2',l.title),el('p',responses.find(r=>r.lesson_id===l.id)?.completed?'Completed ✓':'Learn · Apply · Implement'));const b=el('button','Open lesson →');b.onclick=safe(()=>openLesson(l));card.append(b);$('catalog').append(card);}if(!lessons.length)$('catalog').append(el('p','No published lessons available for your account yet.'));}
async function openLesson(l){selected=l;$('reader').hidden=false;$('module').textContent='MODULE '+l.module_no+' · SECTION '+l.position;$('title').textContent=l.title;$('body').textContent=l.body;$('prompt').textContent=l.prompt;$('media').replaceChildren();$('downloads').replaceChildren();const resources=await rows('resources','lesson_id=eq.'+l.id);for(const r of resources){const url=await signed(r.path);if(r.kind==='video'){const v=el('video');v.controls=true;v.preload='metadata';v.src=url;$('media').append(v);}else{const a=el('a',r.title);a.href=url;a.target='_blank';a.rel='noopener';a.className='button';$('downloads').append(a);}}const answers=await rows('responses','user_id=eq.'+session.user.id+'&lesson_id=eq.'+l.id);$('answer').value=answers[0]?.answer||'';$('completed').checked=answers[0]?.completed||false;$('reader').scrollIntoView({behavior:'smooth'});}
if(!adminPage){$('responseform').onsubmit=safe(async e=>{e.preventDefault();if(!selected)return;await mutate('responses','POST',{user_id:session.user.id,lesson_id:selected.id,answer:$('answer').value,completed:$('completed').checked,updated_at:new Date().toISOString()},'on_conflict=user_id,lesson_id',{Prefer:'resolution=merge-duplicates,return=representation'});status('Your work is saved to your Academy account.');await renderCatalog();});}
async function edit(l){selected=l||null;$('editheading').textContent=l?'Edit lesson':'Create a lesson';$('module_no').value=l?.module_no||1;$('position').value=l?.position||1;$('lesson_title').value=l?.title||'';$('lesson_body').value=l?.body||'';$('lesson_prompt').value=l?.prompt||'';$('published').checked=l?.published||false;$('delete').hidden=!l;$('upload').hidden=!l;$('resources').replaceChildren();if(l)await resourceList();}
async function resourceList(){const rs=await rows('resources','lesson_id=eq.'+selected.id);$('resources').replaceChildren();for(const r of rs){const row=el('p');const a=el('a',r.title+' · '+r.kind);a.href=await signed(r.path);a.target='_blank';a.rel='noopener';const b=el('button','Remove');b.className='secondary';b.onclick=safe(async()=>{if(!confirm('Remove this resource?'))return;await api('/storage/v1/object/sgc-academy-extra',{method:'DELETE',body:{prefixes:[r.path]}});await mutate('resources','DELETE',undefined,'id=eq.'+r.id);await resourceList();status('Resource removed.');});row.append(a,document.createTextNode(' '),b);$('resources').append(row);}}
if(adminPage){
 $('newlesson').onclick=safe(()=>edit(null));
 $('editor').onsubmit=safe(async e=>{e.preventDefault();const data={module_no:Number($('module_no').value),position:Number($('position').value),title:$('lesson_title').value,body:$('lesson_body').value,prompt:$('lesson_prompt').value,published:$('published').checked};const result=await mutate('lessons',selected?'PATCH':'POST',data,selected?'id=eq.'+selected.id:'');lessons=await rows('lessons','order=module_no.asc,position.asc');renderList();await edit(result[0]);status(data.published?'Published. Eligible students can see this lesson now.':'Draft saved.');});
 $('upload').onsubmit=safe(async e=>{e.preventDefault();if(!selected)throw Error('Save a lesson first.');const file=$('file').files[0],kind=$('resource_kind').value;if(!file||file.size>52428800)throw Error('Select a PDF or MP4 below 50 MB.');const type=kind==='video'?'video/mp4':'application/pdf';if(file.type!==type)throw Error(kind==='video'?'Choose an MP4 video.':'Choose a PDF document.');const path=selected.id+'/'+crypto.randomUUID()+ (kind==='video'?'.mp4':'.pdf');status('Uploading…');await api('/storage/v1/object/sgc-academy-extra/'+path,{method:'POST',body:file,headers:{'Content-Type':type}});try{await mutate('resources','POST',{lesson_id:selected.id,title:$('resource_title').value,path,kind});}catch(e){await api('/storage/v1/object/sgc-academy-extra',{method:'DELETE',body:{prefixes:[path]}});throw e;}$('upload').reset();await resourceList();status('Resource uploaded and linked to this lesson.');});
 $('delete').onclick=safe(async()=>{if(!selected||!confirm('Delete this lesson, linked resources and student responses?'))return;const rs=await rows('resources','lesson_id=eq.'+selected.id);if(rs.length)await api('/storage/v1/object/sgc-academy-extra',{method:'DELETE',body:{prefixes:rs.map(r=>r.path)}});await mutate('lessons','DELETE',undefined,'id=eq.'+selected.id);await edit(null);await load();status('Lesson deleted.');});
 $('membersbutton').onclick=safe(async()=>{$('members').hidden=!$('members').hidden;if(!$('members').hidden)await members();});
 $('memberform').onsubmit=safe(async e=>{e.preventDefault();const id=$('user_id').value.trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw Error('Enter the student’s Auth user UUID.');await mutate('members','POST',{user_id:id,joined_at:$('joined_at').value,active:$('active').checked},'on_conflict=user_id',{Prefer:'resolution=merge-duplicates,return=representation'});await members();status('Student access updated.');});
}
async function members(){const ms=await rows('members','order=joined_at.desc');$('memberlist').replaceChildren();const table=el('table');const h=el('tr');['Student UUID','Joined','Access',''].forEach(t=>h.append(el('th',t)));table.append(h);for(const m of ms){const tr=el('tr');[m.user_id,m.joined_at,m.active?'Active':'Paused'].forEach(t=>tr.append(el('td',t)));const td=el('td'),b=el('button','Edit');b.onclick=()=>{$('user_id').value=m.user_id;$('joined_at').value=m.joined_at;$('active').checked=m.active;};td.append(b);tr.append(td);table.append(tr);}$('memberlist').append(table);const rs=await rows('responses','order=updated_at.desc');$('submissions').replaceChildren();for(const r of rs){const box=el('section');box.className='panel';box.append(el('small',r.user_id+' · '+new Date(r.updated_at).toLocaleString()),el('h2',lessons.find(l=>l.id===r.lesson_id)?.title||'Lesson'),el('p',r.completed?'Complete':'In progress'));const answer=el('pre',r.answer);answer.className='content';box.append(answer);$('submissions').append(box);}}
(async()=>{try{if(!cfg?.url.startsWith('https://')||cfg.key.startsWith('PASTE_'))throw Error('Setup needed: add your Supabase project URL and public key to config.js.');const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('access_token')){persist({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),expires_in:Number(hash.get('expires_in')||3600)});history.replaceState(null,'',location.pathname+location.search);if(hash.get('type')==='recovery'){$('login').hidden=true;$('newpass').hidden=false;return;}}else{const saved=sessionStorage.getItem(storageKey);if(saved){session=JSON.parse(saved);await refresh();}}await load();}catch(e){error(e);}})();
