import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const URL='https://bxpexanyoyubxeqqlggh.supabase.co';
const KEY='sb_publishable_Z0_Y-Bj_G5qw4hMgDbQlgA__jj8rGGq';
const db=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const DEFAULT=[{type:'hero',title:'Build your business with confidence',body:'Practical business kits from SGC Network',background:'#f4e7a8'},{type:'text',title:'Choose your business kit',body:'Explore tools and resources designed to help you implement your ideas.',background:'#fbf5ea'}];
let blocks=structuredClone(DEFAULT),selected=0,undo=[],redo=[],dirty=false,loading=false;
const clone=v=>structuredClone(v);
function notify(t){$('notice').textContent=t}
function history(){undo.push(clone(blocks));if(undo.length>60)undo.shift();redo=[];dirty=true;updateButtons()}
function updateButtons(){$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('save').textContent=dirty?'Save draft •':'Save draft'}
function validLink(s){try{const u=new URL(s,location.href);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function safeColor(s){return /^#[0-9a-f]{6}$/i.test(String(s||''))?s:'#ffffff'}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text??'');return n}
function switchView(v){for(const name of ['builder','pages','theme'])$(name+'-panel').hidden=name!==v;document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===v))}
function render(){const list=$('section-list');list.replaceChildren();blocks.forEach((b,i)=>{const row=el('div','section-item'+(selected===i?' active':''));row.draggable=true;row.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',String(i));row.classList.add('dragging')});row.addEventListener('dragend',()=>row.classList.remove('dragging'));row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));if(!Number.isInteger(from)||from<0||from>=blocks.length||from===i)return;history();const [item]=blocks.splice(from,1);blocks.splice(i,0,item);selected=i;render()});const pick=el('button','pick',`${i+1}. ${b.title||b.type}`);pick.onclick=()=>{selected=i;render()};row.append(pick);for(const [label,delta] of [['↑',-1],['↓',1]]){const btn=el('button','mini',label);btn.title='Move section';btn.disabled=i+delta<0||i+delta>=blocks.length;btn.onclick=()=>{history();[blocks[i],blocks[i+delta]]=[blocks[i+delta],blocks[i]];selected=i+delta;render()};row.append(btn)}list.append(row)});inspector();preview();updateButtons()}
function addBlock(type){history();blocks.push({type,title:type==='hero'?'Your headline':type==='cta'?'Explore now':type==='cards'?'What we offer':'New section',body:'',background:'#ffffff',url:'',buttonText:'Explore',cards:type==='cards'?[{title:'First feature',description:'Describe your offer'},{title:'Second feature',description:'Describe your offer'}]:undefined});selected=blocks.length-1;switchView('builder');render()}
function field(parent,key,label,kind='text'){const b=blocks[selected];const l=el('label','',label),input=el(kind==='textarea'?'textarea':'input');if(kind!=='textarea')input.type=kind;input.value=b[key]??(kind==='color'?'#ffffff':'');input.addEventListener('focus',()=>{input.dataset.original=JSON.stringify(b[key]??'')});input.addEventListener('input',()=>{if(!input.dataset.changed){history();input.dataset.changed='1'}b[key]=input.value;if(key==='url'&&b.type==='image')b.imageUrl=input.value;if(key==='url'&&b.type==='cta')b.buttonUrl=input.value;if(key==='title'&&b.type==='cta')b.buttonText=input.value;if(key==='buttonText'&&b.type==='cta')b.title=input.value;dirty=true;preview();updateButtons()});input.addEventListener('change',()=>{delete input.dataset.changed;render()});parent.append(l,input)}
function inspector(){const pane=$('inspector');pane.replaceChildren();const b=blocks[selected];if(!b){pane.append(el('p','muted','Add a section to start designing.'));return}pane.append(el('p','muted',`Editing ${b.type} section`));field(pane,'title','Heading');if(b.type!=='image')field(pane,'body','Description','textarea');field(pane,'background','Background colour','color');if(b.type==='image')field(pane,'url','Image URL (https://)');if(b.type==='cta'){field(pane,'url','Button destination');field(pane,'buttonText','Button text')}if(b.type==='cards'){const label=el('label','','Cards (JSON array)');const input=el('textarea');input.value=JSON.stringify(b.cards||[],null,2);const hint=el('p','muted','Format: [{"title":"...","description":"..."}]');input.addEventListener('change',()=>{try{const val=JSON.parse(input.value);if(!Array.isArray(val)||val.length>30)throw Error('Enter an array of up to 30 cards');history();b.cards=val.map(c=>({title:String(c.title||''),description:String(c.description||'')}));render();notify('Cards updated')}catch(e){notify('Invalid cards: '+e.message)}});pane.append(label,input,hint)}const actions=el('div','inspector-actions');const duplicate=el('button','','Duplicate'),remove=el('button','','Delete');duplicate.onclick=()=>{history();blocks.splice(selected+1,0,clone(b));selected++;render()};remove.onclick=()=>{if(!confirm('Delete this section?'))return;history();blocks.splice(selected,1);selected=Math.max(0,Math.min(selected,blocks.length-1));render()};actions.append(duplicate,remove);pane.append(actions)}
function preview(){const root=$('preview');root.replaceChildren();blocks.forEach((b,i)=>{const section=el('section','preview-section '+(b.type==='hero'?'hero ':'')+(selected===i?'selected':''));section.style.backgroundColor=safeColor(b.background);section.onclick=()=>{if(selected!==i){selected=i;render()}};if(b.type==='image'){const src=validLink(b.url);if(src){const img=el('img');img.src=src;img.alt=b.title||'Image';section.append(img)}}else if(b.type==='cta'){const a=el('span','preview-cta',b.title||b.buttonText||'Explore');section.append(a)}else{section.append(el(b.type==='hero'?'h1':'h2','',b.title||''))}if(b.body)section.append(el('p','',b.body));if(b.type==='cards'){const grid=el('div','preview-cards');(b.cards||[]).forEach(c=>{const card=el('div','preview-card');card.append(el('h3','',c.title||''),el('p','',c.description||''));grid.append(card)});section.append(grid)}root.append(section)})}
async function loadDraft(){if(dirty&&!confirm('Discard unsaved local changes and reload the database draft?'))return;try{notify('Loading draft…');const {data,error}=await db.from('sgc_website_studio_pages').select('draft_content').eq('page_key','kits').single();if(error)throw error;blocks=Array.isArray(data.draft_content)&&data.draft_content.length?clone(data.draft_content):clone(DEFAULT);undo=[];redo=[];dirty=false;selected=0;render();notify('Saved draft loaded')}catch(e){notify('Unable to load draft: '+e.message)}}
async function save(){if(loading)return false;loading=true;try{notify('Saving draft…');const {error}=await db.rpc('sgc_studio_save_draft',{p_page_key:'kits',p_content:blocks});if(error)throw error;dirty=false;updateButtons();notify('Draft saved to Supabase');return true}catch(e){notify('Save failed: '+e.message);return false}finally{loading=false}}
async function publish(){if(!confirm('Publish the Business Kits page? Visitors will see the saved sections.'))return;if(!await save())return;try{const {error}=await db.rpc('sgc_studio_publish',{p_page_key:'kits'});if(error)throw error;notify('Published! Open kits.html and refresh to verify.')}catch(e){notify('Publish failed: '+e.message)}}
async function auth(){try{const {data:{session},error:e}=await db.auth.getSession();if(e||!session){location.replace('../sgc-academy-extra/admin.html');return}const {data:{user},error:ue}=await db.auth.getUser();if(ue||!user){location.replace('../sgc-academy-extra/admin.html');return}const {data:allowed,error:ae}=await db.rpc('sgc_studio_is_admin');if(ae||allowed!==true)throw Error('This account is not authorized to access SGC Studio.');$('gate').hidden=true;$('app').hidden=false;await loadDraft()}catch(e){$('gate-message').textContent=e.message}}
for(const n of document.querySelectorAll('[data-add]'))n.onclick=()=>addBlock(n.dataset.add);
for(const n of document.querySelectorAll('[data-view]'))n.onclick=()=>switchView(n.dataset.view);
for(const n of document.querySelectorAll('[data-device]'))n.onclick=()=>{document.querySelectorAll('[data-device]').forEach(b=>b.classList.toggle('selected',b.dataset.device===n.dataset.device));$('preview').className='preview '+n.dataset.device};
$('open-builder').onclick=()=>switchView('builder');$('reload').onclick=loadDraft;$('reset').onclick=()=>{if(!confirm('Replace your local draft with the starter layout? Save Draft to store this change.'))return;history();blocks=clone(DEFAULT);selected=0;render()};$('save').onclick=save;$('publish').onclick=publish;
$('undo').onclick=()=>{if(!undo.length)return;redo.push(clone(blocks));blocks=undo.pop();selected=Math.min(selected,blocks.length-1);dirty=true;render()};$('redo').onclick=()=>{if(!redo.length)return;undo.push(clone(blocks));blocks=redo.pop();selected=Math.min(selected,blocks.length-1);dirty=true;render()};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});auth();