import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const URL='https://bxpexanyoyubxeqqlggh.supabase.co',KEY='sb_publishable_Z0_Y-Bj_G5qw4hMgDbQlgA__jj8rGGq';
const db=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);
let blocks=[],selected=0,history=[],future=[],view='builder',device='desktop',dirty=false;
const types=['hero','text','image','cta','featured-collection','product-grid','announcement','header','footer','faq','testimonials'];
const defaults=[{type:'hero',title:'Build your business with confidence',body:'Practical business kits from SGC Network',background:'#f4e7a8'},{type:'text',title:'Choose your business kit',body:'Explore resources for your business',background:'#fffaf2'}];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notice=s=>$('notice').textContent=s;
const color=s=>/^#[0-9a-fA-F]{3,8}$/.test(String(s||''))?s:'#ffffff';
const safeUrl=s=>{try{let u=new URL(s,location.origin);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
function checkpoint(){history.push(JSON.stringify(blocks));if(history.length>80)history.shift();future=[];dirty=true}
function mutate(fn){checkpoint();fn();renderBuilder()}
function changeView(v){view=v;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('title').textContent=({builder:'Website Studio',online:'Online Store',themes:'Theme settings',pages:'Pages',navigation:'Navigation',preferences:'Preferences',overview:'Overview',products:'Products',collections:'Collections',orders:'Orders',customers:'Customers',academy:'Academy',settings:'Settings'})[v]||v;$('breadcrumb').textContent=$('title').textContent;const editable=v==='builder';['save','publish','undo','redo'].forEach(id=>$(id).hidden=!editable);renderView()}
function renderView(){const root=$('content');if(view==='builder'){root.innerHTML=`<div class="builder"><div class="side"><h3>Business Kits · Sections</h3><p class="muted mini">Currently connected to the live Kits page. Other pages require individual integration.</p><div id="sectionList"></div><label>Add section</label><select id="newType">${types.map(t=>`<option value="${t}">${esc(t.replaceAll('-',' '))}</option>`).join('')}</select><button id="addSection">+ Add section</button></div><div><div class="toolbar"><button data-device="desktop">Desktop</button><button data-device="tablet">Tablet</button><button data-device="mobile">Mobile</button><a href="../kits.html" target="_blank" rel="noopener">View live kits ↗</a></div><div class="preview-wrap"><div class="preview ${device}" id="preview"></div></div></div><div class="side properties"><h3>Section settings</h3><div id="properties"></div></div></div>`;document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;renderBuilder()});$('addSection').onclick=()=>mutate(()=>{blocks.push({type:$('newType').value,title:'New '+$('newType').value,body:'',background:'#ffffff',url:''});selected=blocks.length-1});renderBuilder();return}
if(view==='pages'){root.innerHTML=`<div class="panel"><h3>Existing SGC pages</h3><p class="hint">The current site files are listed below. Only Business Kits has a connected editable renderer. Opening another page is a preview, not an editable migration.</p>${[['Homepage','../index.html'],['Business Kits','../kits.html'],['Shop','../shop.html'],['Academy','../academy.html'],['Student dashboard','../dashboard.html'],['Community','../community.html'],['Waitlist','../join-academy/']].map(([n,u])=>`<div class="row"><strong>${n}</strong><a href="${u}" target="_blank" rel="noopener">Open live page ↗</a></div>`).join('')}</div>`;return}
if(view==='themes'){root.innerHTML=`<div class="panel"><h3>Theme settings</h3><p class="hint">Global colours, fonts, images, logos and templates require a shared theme renderer on each existing page. They are not connected yet. Use the Business Kits section editor for currently supported background colours.</p><div class="cards">${['Logo & favicon','Color palette','Typography','Buttons','Product cards','Header & footer','Animations','Mobile settings'].map(x=>`<div class="metric">${x}<p class="muted mini">Integration pending</p></div>`).join('')}</div>`;return}
if(view==='overview'){root.innerHTML='<div class="grid">'+['Revenue','Orders','Customers','Products'].map(x=>`<div class="metric">${x}<strong>—</strong><small class="muted">Not connected; no fabricated figures</small></div>`).join('')+'</div><div class="panel"><h3>SGC Structured</h3><p>Website Studio is connected to Business Kits. Business data connections will be added after confirming existing database tables and access policies.</p></div>';return}
root.innerHTML=`<div class="panel"><h3>${esc($('title').textContent)}</h3><p class="hint">This module is planned but is not yet connected to the existing SGC database. No placeholder action here changes live orders, products, collections, menus, metadata, or customer records.</p></div>`}
function renderBuilder(){if(view!=='builder')return;const list=$('sectionList');list.replaceChildren();blocks.forEach((b,i)=>{let el=document.createElement('div');el.className='item'+(i===selected?' selected':'');let top=document.createElement('div');top.className='itemtop';let name=document.createElement('span');name.textContent=(i+1)+'. '+(b.title||b.type);name.onclick=()=>{selected=i;renderBuilder()};let controls=document.createElement('span');[['↑',()=>move(i,-1)],['↓',()=>move(i,1)],['⧉',()=>mutate(()=>{blocks.splice(i+1,0,structuredClone(b));selected=i+1})],['×',()=>{if(confirm('Delete this section from the draft?'))mutate(()=>{blocks.splice(i,1);selected=Math.max(0,Math.min(selected,blocks.length-1))})}]].forEach(([txt,fn])=>{let btn=document.createElement('button');btn.textContent=txt;btn.onclick=fn;controls.append(btn)});top.append(name,controls);el.append(top);list.append(el)});const p=$('properties');p.replaceChildren();let b=blocks[selected];if(b){[['type','Section type','text'],['title','Heading','text'],['body','Description','textarea'],['background','Background colour','color'],['url','Image URL / button link','url'],['buttonText','Button label','text'],['collectionId','Featured collection ID','text'],['productIds','Product IDs (comma separated)','text']].forEach(([key,label,type])=>{let lab=document.createElement('label');lab.textContent=label;let input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=key==='background'?color(b[key]):String(b[key]||'');input.onfocus=()=>checkpoint();input.oninput=()=>{b[key]=input.value;dirty=true;renderPreview()};input.onchange=()=>renderBuilder();p.append(lab,input)})}else p.textContent='Add a section to begin';renderPreview()}
function move(i,d){const j=i+d;if(j<0||j>=blocks.length)return;mutate(()=>{[blocks[i],blocks[j]]=[blocks[j],blocks[i]];selected=j})}
function renderPreview(){if(view!=='builder')return;let r=$('preview');r.className='preview '+device;r.replaceChildren();blocks.forEach(b=>{let s=document.createElement('section');s.className='block '+(b.type==='hero'?'hero':'');s.style.backgroundColor=color(b.background);let h=document.createElement('h2');h.textContent=b.title||b.type;s.append(h);if(b.type==='image'&&safeUrl(b.url)){let img=document.createElement('img');img.src=safeUrl(b.url);img.alt=b.title||'';s.append(img)}if(b.body){let p=document.createElement('p');p.textContent=b.body;s.append(p)}if(b.type==='cta'||b.buttonText){let a=document.createElement('a');a.textContent=b.buttonText||b.title||'Learn more';a.href=safeUrl(b.url)||'#';a.onclick=e=>e.preventDefault();s.append(a)}if(['featured-collection','product-grid'].includes(b.type)){let msg=document.createElement('p');msg.className='muted';msg.textContent='Product/collection display requires a linked catalogue renderer; not yet live.';s.append(msg)}r.append(s)})}
async function load(){const {data,error}=await db.from('sgc_website_studio_pages').select('draft_content').eq('page_key','kits').single();if(error)throw error;blocks=Array.isArray(data.draft_content)&&data.draft_content.length?data.draft_content:structuredClone(defaults);selected=0;history=[];future=[];dirty=false;changeView('builder');notice('Business Kits draft loaded')}
async function save(){try{const {error}=await db.rpc('sgc_studio_save_draft',{p_page_key:'kits',p_content:blocks});if(error)throw error;dirty=false;notice('Draft saved')}catch(e){notice('Save failed: '+e.message)}}
async function publish(){if(!confirm('Publish the Business Kits draft to your live site?'))return;try{const saved=await db.rpc('sgc_studio_save_draft',{p_page_key:'kits',p_content:blocks});if(saved.error)throw saved.error;const {error}=await db.rpc('sgc_studio_publish',{p_page_key:'kits'});if(error)throw error;dirty=false;notice('Business Kits published. Check the live page.') }catch(e){notice('Publish failed: '+e.message)}}
$('save').onclick=save;$('publish').onclick=publish;$('undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(blocks));blocks=JSON.parse(history.pop());renderBuilder()};$('redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(blocks));blocks=JSON.parse(future.pop());renderBuilder()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>changeView(b.dataset.view));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{try{const {data:{session}}=await db.auth.getSession();if(!session){location.replace('../sgc-academy-extra/admin.html');return}const {data:allowed,error}=await db.rpc('sgc_studio_is_admin');if(error||allowed!==true)throw new Error('This account is not authorised for SGC Studio');$('app').hidden=false;$('state').textContent='Admin verified';await load()}catch(e){$('state').textContent=e.message;notice(e.message)}})();
